export const stateList = [
  { id: 12, value: "AC", text: "Acre" },
  { id: 27, value: "AL", text: "Alagoas" },
  { id: 16, value: "AP", text: "Amapá" },
  { id: 13, value: "AM", text: "Amazonas" },
  { id: 29, value: "BA", text: "Bahia" },
  { id: 23, value: "CE", text: "Ceará" },
  { id: 53, value: "DF", text: "Distrito Federal" },
  { id: 32, value: "ES", text: "Espírito Santo" },
  { id: 52, value: "GO", text: "Goiás" },
  { id: 21, value: "MA", text: "Maranhão" },
  { id: 51, value: "MT", text: "Mato Grosso" },
  { id: 50, value: "MS", text: "Mato Grosso do Sul" },
  { id: 31, value: "MG", text: "Minas Gerais" },
  { id: 15, value: "PA", text: "Pará" },
  { id: 25, value: "PB", text: "Paraíba" },
  { id: 41, value: "PR", text: "Paraná" },
  { id: 26, value: "PE", text: "Pernambuco" },
  { id: 22, value: "PI", text: "Piauí" },
  { id: 33, value: "RJ", text: "Rio de Janeiro" },
  { id: 24, value: "RN", text: "Rio Grande do Norte" },
  { id: 43, value: "RS", text: "Rio Grande do Sul" },
  { id: 11, value: "RO", text: "Rondônia" },
  { id: 14, value: "RR", text: "Roraima" },
  { id: 42, value: "SC", text: "Santa Catarina" },
  { id: 35, value: "SP", text: "São Paulo" },
  { id: 28, value: "SE", text: "Sergipe" },
  { id: 17, value: "TO", text: "Tocantins" },
];
